version: "3"
services:
  client_app:
    container_name: client_app
    build: ./client
    volumes:
      - ./client:/home/node/client
      - /home/node/client/node_modules
    networks:
      - mern_app
  api_server:
    container_name: api_server
    build: ./server
    environment:
      - DATABASE_URL=postgres://user:pass@db_server:5432/db
      - NODE_ENV=development
    volumes:
      - ./server:/home/node/server
      - /home/node/server/node_modules
    networks:
      - mern_app
  db_server:
    container_name: db_server
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    volumes:
      - ./.pg-data/postgresql/data:/var/lib/postgresql/data
    networks:
      - mern_app
  reverse_proxy:
    container_name: ngnix
    restart: unless-stopped
    image: nginx:1.21.4
    ports:
      - 80:80
    depends_on:
      - api_server
      - client_app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mern_app
networks:
  mern_app:
    driver: bridge
