version: "3"
services:
  client_app:
    container_name: client_app
    build: ./client
    environment:
      - PORT=80
      - CHOKIDAR_USEPOLLING="true"
    volumes:
      - ./client:/home/node/client
      - /home/node/client/node_modules
    depends_on:
      - api_server
    networks:
      - mern_app
  nest_api_server:
    container_name: nest_api_server
    build: ./nest-server
    environment:
      - DATABASE_URL=postgres://user:pass@db_server:5432/app
      - NODE_ENV=development
      - ACCESS_TOKEN_SECRET=4e7cd74b005aa9a6a550875b2908bf56b10103341b60ef7c952c03e8b6bbff9b7b8d01cbc7352b79bebe91295c6b4b4cf2312970df555aa50df6eb167ff8ef17
    volumes:
      - ./nest-server:/home/node/nest-server
      - /home/node/nest-server/node_modules
    depends_on:
      - db_server
    networks:
      - mern_app
  db_server:
    container_name: db_server
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app
    volumes:
      - /var/lib/postgresql/data
    networks:
      - mern_app
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=pgsql
    depends_on:
      - db_server
    networks:
      - mern_app
  reverse_proxy:
    container_name: ngnix
    restart: unless-stopped
    image: nginx:1.21.4
    ports:
      - 80:80
    depends_on:
      - api_server
      - client_app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mern_app
networks:
  mern_app:
    driver: bridge
